version: "3.9"

services:
  db:
    image: postgres:16
    container_name: study_desk_db
    restart: always

    environment:
      POSTGRES_USER: study_user
      POSTGRES_PASSWORD: study_pass
      POSTGRES_DB: study_desk

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
